version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  mobileseriousgame.api:
    image: mobileseriousgame.api
    build:
      context: .
      dockerfile: MobileSeriousGame.API/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: "https://+;http://+"
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      JWT_KEY: ${JWT_KEY}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      JWT_EXPIRATION_IN_MINUTES: ${JWT_EXPIRATION}
    depends_on:
      - mysql
    restart: always
    entrypoint: [ "sh", "-c", "sleep 10 && dotnet MobileSeriousGame.API.dll" ]

volumes:
  mysql_data: